In [1]:
import numpy as np 
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
arr = np.array([
    [-1, 2, 0, 4],
    [4, -0.5, 6, 0],
    [2.6, 0, 7, 8],
    [3, -7, 4, 2.0]
])

arr2 = arr[:2, ::2]
print("First 2 rows and alternate columns:\n", arr2)


First 2 rows and alternate columns:
 [[-1.  0.]
 [ 4.  6.]]


In [7]:
x = np.array([1,2])
print(x.dtype)

y = np.array([1.0,2.0])
print(y.dtype)

int32
float64


In [12]:
zeros = np.zeros((3, 4))
print("\nZeros array:\n", zeros)


Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
reshaped = np.arange(1, 13).reshape(3, 4)
print("\nReshaped array:\n", reshaped)


Reshaped array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
import pandas as pd
data = np.array(['g', 'e', 'e', 'k', 's'])
s = pd.Series(data)
print("Pandas Series:")
print(s)

Pandas Series:
0    g
1    e
2    e
3    k
4    s
dtype: object


In [15]:
df = pd.DataFrame() 
print(df)
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks'] 
  
df = pd.DataFrame(lst) 
print(df)

Empty DataFrame
Columns: []
Index: []
        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks


In [18]:
data = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks']
df = pd.DataFrame(data, columns=['Words'])
print(df)

    Words
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks


In [20]:
arr1 = np.array([1,2,3])
print(arr)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
